name: Test Setup
description: Set up Neovim, Lua, Luarocks, busted, and guard.nvim

runs:
  using: composite
  steps:
    - uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: nightly
    - uses: leso-kn/gh-actions-lua@master
      with:
        luaVersion: "5.1"
    - uses: hishamhm/gh-actions-luarocks@master
    - name: Install busted and nlua
      shell: bash
      run: |
        luarocks install busted --local
        luarocks install nlua --local
    - name: Clone guard.nvim
      shell: bash
      run: git clone --depth 1 https://github.com/nvimdev/guard.nvim && mv guard.nvim/lua/guard lua/
