name: Test Setup
description: Install Neovim, Lua 5.1, Luarocks, busted, nlua, and guard.nvim

runs:
  using: composite
  steps:
    - uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: nightly
    - uses: leso-kn/gh-actions-lua@master
      with:
        luaVersion: '5.1'
    - uses: hishamhm/gh-actions-luarocks@master
    - run: luarocks install busted --local && luarocks install nlua --local
      shell: bash
    - run: git clone --depth 1 https://github.com/nvimdev/guard.nvim && mv guard.nvim/lua/guard lua/
      shell: bash
